In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [3]:
manga = pd.read_csv('./data/data.csv')

In [5]:
manga.head()

,title,description,rating,year,tags,cover
0,Salad Days (Tang LiuZang) - Part 2,The second season of Salad Days (Tang LiuZang).,4.7,2021.0,"['BL', 'Manhua', 'Romance', 'Shounen-ai', 'Spo...",https://cdn.anime-planet.com/manga/primary/sal...
1,The Master of Diabolism,As the grandmaster who founded the Demonic Sec...,4.7,2017.0,"['Action', 'Adventure', 'BL', 'Comedy', 'Manhu...",https://cdn.anime-planet.com/manga/primary/the...
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,"Set in 1890, Steel Ball Run spotlights Gyro Ze...",4.7,2004.0,"['Action', 'Adventure', 'Horror', 'Mystery', '...",https://cdn.anime-planet.com/manga/primary/joj...
3,A Sign of Affection,"Yuki is a typical college student, whose world...",4.7,2019.0,"['Romance', 'Shoujo', 'Slice of Life', 'Disabi...",https://cdn.anime-planet.com/manga/primary/a-s...
4,Moriarty the Patriot,"Before he was Sherlock’s rival, Moriarty fough...",4.7,2016.0,"['Mystery', 'Shounen', 'Detectives', 'England'...",https://cdn.anime-planet.com/manga/primary/mor...

In [7]:
manga.shape

(70948, 6)

In [95]:
manga.isnull().sum()

title          0
fulltag        0
description    0
rating         0
tags           0
dtype: int64

In [97]:
manga.dtypes

title           object
fulltag         object
description     object
rating         float64
tags            object
dtype: object

In [13]:
manga.dropna(inplace=True)

In [15]:
manga = manga[manga['rating'] >= 4]

In [17]:
manga.duplicated().sum()

0

In [19]:
manga = manga.drop('cover', axis=1)

In [21]:
temp_df = manga.copy()

In [23]:
temp_df.head()

,title,description,rating,year,tags
0,Salad Days (Tang LiuZang) - Part 2,The second season of Salad Days (Tang LiuZang).,4.7,2021.0,"['BL', 'Manhua', 'Romance', 'Shounen-ai', 'Spo..."
1,The Master of Diabolism,As the grandmaster who founded the Demonic Sec...,4.7,2017.0,"['Action', 'Adventure', 'BL', 'Comedy', 'Manhu..."
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,"Set in 1890, Steel Ball Run spotlights Gyro Ze...",4.7,2004.0,"['Action', 'Adventure', 'Horror', 'Mystery', '..."
3,A Sign of Affection,"Yuki is a typical college student, whose world...",4.7,2019.0,"['Romance', 'Shoujo', 'Slice of Life', 'Disabi..."
4,Moriarty the Patriot,"Before he was Sherlock’s rival, Moriarty fough...",4.7,2016.0,"['Mystery', 'Shounen', 'Detectives', 'England'..."

In [25]:
import ast

temp_df['tags'] = temp_df['tags'].apply(lambda x: ", ".join(ast.literal_eval(x)))

In [27]:
temp_df.head()

,title,description,rating,year,tags
0,Salad Days (Tang LiuZang) - Part 2,The second season of Salad Days (Tang LiuZang).,4.7,2021.0,"BL, Manhua, Romance, Shounen-ai, Sports, Webto..."
1,The Master of Diabolism,As the grandmaster who founded the Demonic Sec...,4.7,2017.0,"Action, Adventure, BL, Comedy, Manhua, Mystery..."
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,"Set in 1890, Steel Ball Run spotlights Gyro Ze...",4.7,2004.0,"Action, Adventure, Horror, Mystery, Seinen, 19..."
3,A Sign of Affection,"Yuki is a typical college student, whose world...",4.7,2019.0,"Romance, Shoujo, Slice of Life, Disability"
4,Moriarty the Patriot,"Before he was Sherlock’s rival, Moriarty fough...",4.7,2016.0,"Mystery, Shounen, Detectives, England, Europe,..."

In [29]:
manga['description'] = manga['description'].apply(lambda x : x.split())

In [31]:
manga.head()

,title,description,rating,year,tags
0,Salad Days (Tang LiuZang) - Part 2,"[The, second, season, of, Salad, Days, (Tang, ...",4.7,2021.0,"['BL', 'Manhua', 'Romance', 'Shounen-ai', 'Spo..."
1,The Master of Diabolism,"[As, the, grandmaster, who, founded, the, Demo...",4.7,2017.0,"['Action', 'Adventure', 'BL', 'Comedy', 'Manhu..."
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,"[Set, in, 1890,, Steel, Ball, Run, spotlights,...",4.7,2004.0,"['Action', 'Adventure', 'Horror', 'Mystery', '..."
3,A Sign of Affection,"[Yuki, is, a, typical, college, student,, whos...",4.7,2019.0,"['Romance', 'Shoujo', 'Slice of Life', 'Disabi..."
4,Moriarty the Patriot,"[Before, he, was, Sherlock’s, rival,, Moriarty...",4.7,2016.0,"['Mystery', 'Shounen', 'Detectives', 'England'..."

In [33]:
manga.iloc[0]['tags']

"['BL', 'Manhua', 'Romance', 'Shounen-ai', 'Sports', 'Webtoons', 'Full Color']"

In [35]:
import re

def clean_description(word):
    l = []
    for i in word:
        cleaned = re.sub(r"[()\-\s]", "", i)
        l.append(cleaned)
    return l

In [37]:
import ast 

def clean_tags(word):
    if isinstance(word, str):
        word = ast.literal_eval(word)  
    
    l = []
    for i in word:
        cleaned = i.replace(" ", "").replace("-", "")
        l.append(cleaned)
    return l

In [39]:
def remove_space(word):
    l = []
    for i in word:
        l.append(i.replace(" ", ""))
    return l

In [41]:
manga['description'] = manga['description'].apply(remove_space)
manga['tags'] = manga['tags'].apply(clean_tags)

In [43]:
manga.head()

,title,description,rating,year,tags
0,Salad Days (Tang LiuZang) - Part 2,"[The, second, season, of, Salad, Days, (Tang, ...",4.7,2021.0,"[BL, Manhua, Romance, Shounenai, Sports, Webto..."
1,The Master of Diabolism,"[As, the, grandmaster, who, founded, the, Demo...",4.7,2017.0,"[Action, Adventure, BL, Comedy, Manhua, Myster..."
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,"[Set, in, 1890,, Steel, Ball, Run, spotlights,...",4.7,2004.0,"[Action, Adventure, Horror, Mystery, Seinen, 1..."
3,A Sign of Affection,"[Yuki, is, a, typical, college, student,, whos...",4.7,2019.0,"[Romance, Shoujo, SliceofLife, Disability]"
4,Moriarty the Patriot,"[Before, he, was, Sherlock’s, rival,, Moriarty...",4.7,2016.0,"[Mystery, Shounen, Detectives, England, Europe..."

In [45]:
manga['fulltag'] = manga['description'] + manga['tags']

In [47]:
manga.head()

,title,description,rating,year,tags,fulltag
0,Salad Days (Tang LiuZang) - Part 2,"[The, second, season, of, Salad, Days, (Tang, ...",4.7,2021.0,"[BL, Manhua, Romance, Shounenai, Sports, Webto...","[The, second, season, of, Salad, Days, (Tang, ..."
1,The Master of Diabolism,"[As, the, grandmaster, who, founded, the, Demo...",4.7,2017.0,"[Action, Adventure, BL, Comedy, Manhua, Myster...","[As, the, grandmaster, who, founded, the, Demo..."
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,"[Set, in, 1890,, Steel, Ball, Run, spotlights,...",4.7,2004.0,"[Action, Adventure, Horror, Mystery, Seinen, 1...","[Set, in, 1890,, Steel, Ball, Run, spotlights,..."
3,A Sign of Affection,"[Yuki, is, a, typical, college, student,, whos...",4.7,2019.0,"[Romance, Shoujo, SliceofLife, Disability]","[Yuki, is, a, typical, college, student,, whos..."
4,Moriarty the Patriot,"[Before, he, was, Sherlock’s, rival,, Moriarty...",4.7,2016.0,"[Mystery, Shounen, Detectives, England, Europe...","[Before, he, was, Sherlock’s, rival,, Moriarty..."

In [49]:
manga['fulltag'] = manga['fulltag'].apply(lambda x:" ".join(x))

In [51]:
manga.head()

,title,description,rating,year,tags,fulltag
0,Salad Days (Tang LiuZang) - Part 2,"[The, second, season, of, Salad, Days, (Tang, ...",4.7,2021.0,"[BL, Manhua, Romance, Shounenai, Sports, Webto...",The second season of Salad Days (Tang LiuZang)...
1,The Master of Diabolism,"[As, the, grandmaster, who, founded, the, Demo...",4.7,2017.0,"[Action, Adventure, BL, Comedy, Manhua, Myster...",As the grandmaster who founded the Demonic Sec...
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,"[Set, in, 1890,, Steel, Ball, Run, spotlights,...",4.7,2004.0,"[Action, Adventure, Horror, Mystery, Seinen, 1...","Set in 1890, Steel Ball Run spotlights Gyro Ze..."
3,A Sign of Affection,"[Yuki, is, a, typical, college, student,, whos...",4.7,2019.0,"[Romance, Shoujo, SliceofLife, Disability]","Yuki is a typical college student, whose world..."
4,Moriarty the Patriot,"[Before, he, was, Sherlock’s, rival,, Moriarty...",4.7,2016.0,"[Mystery, Shounen, Detectives, England, Europe...","Before he was Sherlock’s rival, Moriarty fough..."

In [53]:
manga['fulltag'] = manga['fulltag'].apply(lambda x:x.lower())

In [55]:
manga.iloc[0]['fulltag']

'the second season of salad days (tang liuzang). bl manhua romance shounenai sports webtoons fullcolor'

In [57]:
import nltk
from nltk.stem import PorterStemmer

ps = PorterStemmer()

In [59]:
def stems(text):
    l = []
    for i in text.split():
        l.append(ps.stem(i))
    return " ".join(l)

In [61]:
manga['fulltag'] = manga['fulltag'].apply(stems)

In [63]:
manga.iloc[3]['fulltag']

'yuki is a typic colleg student, whose world revolv around her friends, social media, and the latest sales. but when a chanc encount on a train lead to her meet friend-of-a-friend and fellow student itsuomi-san, her world start to widen. but even though itsuomi-kun can speak three languages, sign languag isn’t one of them. can the two learn to commun the bud feel between them? romanc shoujo sliceoflif disabl'

In [65]:
manga = manga[['title', 'fulltag']]

In [67]:
manga.head()

,title,fulltag
0,Salad Days (Tang LiuZang) - Part 2,the second season of salad day (tang liuzang)....
1,The Master of Diabolism,"as the grandmast who found the demon sect, wei..."
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,"set in 1890, steel ball run spotlight gyro zep..."
3,A Sign of Affection,"yuki is a typic colleg student, whose world re..."
4,Moriarty the Patriot,"befor he wa sherlock’ rival, moriarti fought a..."

In [69]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=11000, stop_words='english')

In [71]:
vector = cv.fit_transform(manga['fulltag']).toarray()

In [73]:
vector.shape

(10960, 11000)

In [75]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)

In [77]:
similarity.shape

(10960, 10960)

In [107]:
def keep_top_n_per_row(similarity_matrix, n=20):
    # similarity_matrix: NxN numpy array
    top_n_sim = np.zeros_like(similarity_matrix)  # same shape, zeros

    for i in range(similarity_matrix.shape[0]):
        row = similarity_matrix[i]
        # Get indices of top n similarities excluding self (which should be 1 at diagonal)
        # We keep top n+1 to account for self, then exclude self index
        top_indices = np.argpartition(row, - (n + 1))[-(n + 1):]
        
        # Remove self index (similarity with itself)
        top_indices = top_indices[top_indices != i]
        
        # If more than n after excluding self, keep only top n
        if len(top_indices) > n:
            top_indices = top_indices[np.argsort(row[top_indices])[-n:]]

        # Assign the values to zeroed matrix
        top_n_sim[i, top_indices] = row[top_indices]

        # Also keep self similarity 1.0 (optional)
        top_n_sim[i, i] = 1.0
    
    return top_n_sim

In [111]:
similarity_reduced = keep_top_n_per_row(similarity, n=20)

print(similarity_reduced.shape)

(10960, 10960)

In [105]:
manga[manga['title'] == 'Dragon Ball'].index[0]

596

In [113]:
def recommend(manga_title):
    index = manga[manga['title'] == manga_title].index[0]
    distances = sorted(list(enumerate(similarity_reduced[index])), reverse=True, key=lambda x: x[1])
    for i in distances[1:6]:
        print(manga.iloc[i[0]].title)

In [115]:
recommend('Murim Login')

Yaseppochi to Futoccho
To Match a Villainess: Love Hunting Rhapsody
The Seven Deadly Sins: Seven-Colored Recollections (Light Novel)
Life Going Wild With Plug-ins
Born from Death

In [85]:
manga = manga.merge(temp_df[['title', 'description', 'rating', 'tags']], on='title', how='left')

In [99]:
manga.head()

,title,fulltag,description,rating,tags
0,Salad Days (Tang LiuZang) - Part 2,the second season of salad day (tang liuzang)....,The second season of Salad Days (Tang LiuZang).,4.7,"BL, Manhua, Romance, Shounen-ai, Sports, Webto..."
1,The Master of Diabolism,"as the grandmast who found the demon sect, wei...",As the grandmaster who founded the Demonic Sec...,4.7,"Action, Adventure, BL, Comedy, Manhua, Mystery..."
2,JoJo's Bizarre Adventure Part 7: Steel Ball Run,"set in 1890, steel ball run spotlight gyro zep...","Set in 1890, Steel Ball Run spotlights Gyro Ze...",4.7,"Action, Adventure, Horror, Mystery, Seinen, 19..."
3,A Sign of Affection,"yuki is a typic colleg student, whose world re...","Yuki is a typical college student, whose world...",4.7,"Romance, Shoujo, Slice of Life, Disability"
4,Moriarty the Patriot,"befor he wa sherlock’ rival, moriarti fought a...","Before he was Sherlock’s rival, Moriarty fough...",4.7,"Mystery, Shounen, Detectives, England, Europe,..."

In [117]:
import gzip
import pickle

with gzip.open('artifacts/manga_list.pkl.gz', 'wb') as f:
    pickle.dump(manga, f)

with gzip.open('artifacts/similarity.pkl.gz', 'wb') as f:
    pickle.dump(similarity_reduced, f)

In [437]:
import pickle

pickle.dump(manga, open('artifacts/manga_list.pkl', 'wb'))
pickle.dump(similarity, open('artifacts/similarity.pkl', 'wb'))